import type { DerivedConfig } from "../derive.js";

/**
 * Generates the Caddyfile: one site block per enabled service, with SSE
 * friendly settings (no buffering, no read/write timeouts).
 */
export function generateCaddyfile(derived: DerivedConfig): string {
  const { answers } = derived;
  const acme = answers.tls === "caddy-acme";

  const out: string[] = [];
  out.push("# Caddyfile generated by the MySagra installer");
  out.push("# SSE friendly: response buffering disabled and proxy timeouts removed.");

  // ── global options ──
  out.push("{");
  if (acme && answers.acmeEmail) out.push(`\temail ${answers.acmeEmail}`);
  if (derived.hasIpAccess) {
    // clients connecting to https://<ip> send no SNI: serve the IP certificate
    out.push(`\tdefault_sni ${answers.serverIp}`);
  }
  out.push("\tservers {");
  out.push("\t\tprotocols h1 h2 h3");
  out.push("\t}");
  out.push("}");
  out.push("");

  // reusable SSE-safe reverse proxy snippet
  out.push("(sse_proxy) {");
  out.push("\treverse_proxy {args[0]} {");
  out.push("\t\tflush_interval -1");
  out.push("\t\theader_up X-Real-IP {remote_host}");
  out.push("\t\theader_down X-Accel-Buffering no");
  out.push("\t\ttransport http {");
  out.push("\t\t\tread_timeout 0");
  out.push("\t\t\twrite_timeout 0");
  out.push("\t\t\tdial_timeout 10s");
  out.push("\t\t}");
  out.push("\t}");
  out.push("}");
  out.push("");

  out.push("(common) {");
  out.push("\tencode zstd gzip {");
  out.push("\t\tmatch {");
  out.push("\t\t\theader Content-Type text/*");
  out.push("\t\t\theader Content-Type application/json*");
  out.push("\t\t\theader Content-Type application/javascript*");
  out.push("\t\t\theader Content-Type image/svg+xml*");
  out.push("\t\t}");
  out.push("\t\t# text/event-stream is never compressed (SSE)");
  out.push("\t}");
  out.push("\theader {");
  out.push("\t\tX-Content-Type-Options nosniff");
  out.push("\t\tX-Frame-Options SAMEORIGIN");
  out.push("\t\tReferrer-Policy strict-origin-when-cross-origin");
  if (acme) {
    out.push('\t\tStrict-Transport-Security "max-age=31536000; includeSubDomains"');
  }
  out.push("\t\t-Server");
  out.push("\t}");
  out.push("\tlog {");
  out.push("\t\toutput stdout");
  out.push("\t\tformat console");
  out.push("\t}");
  out.push("}");
  out.push("");

  for (const endpoint of derived.endpoints) {
    const upstream = `${endpoint.service.id}:${endpoint.service.port}`;
    // hostname and (in hybrid mode) the direct https://<ip>:<port> address share
    // the same site block, so both are served with the same certificate rules
    const addresses = [endpoint.host];
    if (endpoint.ipUrl) {
      addresses.push(
        endpoint.service.ipPort === 443
          ? `https://${derived.answers.serverIp}`
          : `https://${derived.answers.serverIp}:${endpoint.service.ipPort}`,
      );
    }
    out.push(`# ${endpoint.service.label} — ${endpoint.service.description}`);
    out.push(`${addresses.join(", ")} {`);
    if (!acme) out.push("\ttls internal");
    out.push("\timport common");
    out.push(`\timport sse_proxy ${upstream}`);
    out.push("}");
    out.push("");
  }

  return out.join("\n");
}
