import type { DerivedConfig, ServiceEndpoint } from "../derive.js";
import { renderEnvFile, type EnvSection } from "../env-file.js";
import { API_KEY_PLACEHOLDER, type Secrets } from "../secrets.js";
import { endpointFor } from "../derive.js";

export const DB_NAME = "mysagra";
export const DB_USER = "mysagra";

/**
 * Builds the .env file. Only the sections relevant to the selected services are
 * written: e.g. the API keys appear only with MyStampa/MyClienti and the DBGate
 * credentials only with the `dbgate` profile.
 */
export function generateEnv(
  derived: DerivedConfig,
  secrets: Secrets,
  existing: Record<string, string> = {},
): string {
  const { answers } = derived;
  const bool = (v: boolean) => (v ? "true" : "false");
  const enabled = (profile: string) => answers.services.includes(profile as never);
  const urlOf = (id: string): ServiceEndpoint | undefined => endpointFor(derived, id);

  const header = [
    "Generated by the MySagra installer — do NOT commit this file.",
    `Generated at ${new Date().toISOString()}`,
    "Secrets were generated locally with node:crypto.",
  ];

  const sections: EnvSection[] = [];

  sections.push({
    title: "General",
    entries: [
      [
        "COMPOSE_PROJECT_NAME",
        answers.projectName,
        "Docker project name: also prefixes container and volume names",
      ],
      [
        "COMPOSE_PROFILES",
        derived.composeProfiles,
        "Enabled profiles: `docker compose up -d` only starts these services",
      ],
      ["SETUP_MODE", answers.setup, "simple = bundled Caddy, advanced = external proxy"],
      ...(answers.setup === "advanced"
        ? ([["STACK_NAME", answers.stackName, "Identifier of this stack instance"]] as Array<
            [string, string, string]
          >)
        : []),
      ["NODE_ENV", answers.nodeEnv],
      ["SERVER_IP", answers.serverIp, "Address of the server hosting the stack"],
      ...(derived.proxyEnabled
        ? ([
            ["DNS_MODE", answers.dns, "hybrid = hostnames + direct IP, sslip, manual"],
            [
              "BASE_DOMAIN",
              answers.baseDomain,
              "Hostnames are <service>-[HOST_PREFIX-]<BASE_DOMAIN>",
            ],
            ...(answers.hostPrefix ? [["HOST_PREFIX", answers.hostPrefix, "Instance prefix"]] : []),
            ["TLS_MODE", answers.tls, "caddy-internal = local CA, caddy-acme = Let's Encrypt"],
            ...(answers.acmeEmail ? [["ACME_EMAIL", answers.acmeEmail]] : []),
          ] as Array<[string, string, string?]>)
        : ([
            [
              "PUBLISH_PORTS",
              answers.publishPorts ? "true" : "false",
              "Service ports published on the host",
            ],
            ...(answers.publishPorts
              ? [["PORT_OFFSET", String(answers.portOffset), "Added to every published host port"]]
              : []),
            ...(answers.externalDomain
              ? [["EXTERNAL_DOMAIN", answers.externalDomain, "Domain served by your reverse proxy"]]
              : []),
          ] as Array<[string, string, string?]>)),
      [
        "API_URL",
        derived.api.url,
        derived.proxyEnabled
          ? "Public URL of the MySagra API (through Caddy)"
          : "Public URL of the MySagra API (through your proxy)",
      ],
      ["INTERNAL_API_URL", derived.internalApiUrl, "API URL inside the docker network"],
      ...(derived.api.hostPort
        ? ([["PORT_API", String(derived.api.hostPort), "Published host port of the API"]] as Array<
            [string, string, string]
          >)
        : []),
      ["REQUIRE_TABLE", bool(answers.requireTable), "Ask the customer for a table number"],
      [
        "SHOW_NUMBERS",
        bool(answers.showNumbers),
        "Use the sequential order number instead of the display code",
      ],
    ],
  });

  if (answers.setup === "advanced") {
    const connectorEntries: EnvSection["entries"] = [
      ["CONNECTOR", answers.connector, "none | cloudflare | nginx"],
    ];
    if (derived.cloudflareEnabled) {
      connectorEntries.push([
        "CLOUDFLARE_TUNNEL_TOKEN",
        answers.cloudflareToken,
        "Token of the tunnel connector (Zero Trust dashboard)",
      ]);
    }
    if (derived.nginxEnabled) {
      connectorEntries.push([
        "NGINX_PORTS",
        `${80 + answers.portOffset}, ${443 + answers.portOffset}`,
        "Host ports published by the nginx container (edit in docker-compose.yml)",
      ]);
    }
    sections.push({ title: "Connector", entries: connectorEntries });
  }

  // ── API keys: only for the services that authenticate with one ──
  const apiKeyEntries: EnvSection["entries"] = [];
  if (enabled("mystampa")) {
    apiKeyEntries.push([
      "MYSTAMPA_API_KEY",
      // keep a key already pasted by the user
      existing.MYSTAMPA_API_KEY || API_KEY_PLACEHOLDER.mystampa,
      "Create a PRINTER key in the admin panel and paste it here",
    ]);
  }
  if (enabled("myclienti")) {
    apiKeyEntries.push([
      "MYCLIENTI_API_KEY",
      existing.MYCLIENTI_API_KEY || API_KEY_PLACEHOLDER.myclienti,
      "Create a WEBAPP key in the admin panel and paste it here",
    ]);
  }
  if (apiKeyEntries.length) sections.push({ title: "API Keys", entries: apiKeyEntries });

  sections.push({
    title: "MySagra Backend",
    entries: [
      ["PEPPER", secrets.PEPPER!],
      ["JWT_SECRET", secrets.JWT_SECRET!],
      ["ALLOWED_ORIGINS", derived.allowedOrigins],
      [
        "TRUST_PROXY_LEVEL",
        String(answers.trustProxyLevel),
        "Number of trusted proxies in front of the backend",
      ],
    ],
  });

  sections.push({
    title: "Database",
    entries: [
      ["MYSQL_DATABASE", DB_NAME],
      ["DB_USER", DB_USER],
      ["DB_USER_PASSWORD", secrets.DB_USER_PASSWORD!],
      ["ROOT_PASSWORD", secrets.ROOT_PASSWORD!],
      [
        "DATABASE_URL",
        `mysql://${DB_USER}:${secrets.DB_USER_PASSWORD}@db:3306/${DB_NAME}`,
        "Used by the backend (internal docker network)",
      ],
    ],
  });

  sections.push({
    title: "Redis",
    entries: [
      ["REDIS_PASS", secrets.REDIS_PASS!],
      ["REDIS_URL", `redis://:${secrets.REDIS_PASS}@redis:6379`],
    ],
  });

  const portEntry = (e?: ServiceEndpoint, name?: string): EnvSection["entries"] =>
    e?.hostPort && name ? [[name, String(e.hostPort), "Published host port"]] : [];

  if (enabled("mycassa")) {
    const e = urlOf("mycassa");
    sections.push({
      title: "MyCassa",
      entries: [
        ["AUTH_URL_CASSA", derived.api.url],
        ...(e ? [["URL_MYCASSA", e.url] as [string, string]] : []),
        ...(e?.ipUrl ? [["URL_MYCASSA_IP", e.ipUrl] as [string, string]] : []),
        ...portEntry(e, "PORT_MYCASSA"),
      ],
    });
  }

  if (enabled("myadmin")) {
    const e = urlOf("myamministratore");
    sections.push({
      title: "MyAmministratore",
      entries: [
        ["AUTH_URL_AMMINISTRATORE", derived.api.url],
        ...(e ? [["URL_MYAMMINISTRATORE", e.url] as [string, string]] : []),
        ...(e?.ipUrl ? [["URL_MYAMMINISTRATORE_IP", e.ipUrl] as [string, string]] : []),
        ...portEntry(e, "PORT_MYAMMINISTRATORE"),
      ],
    });
  }

  if (enabled("mystampa")) {
    const e = urlOf("mystampa");
    sections.push({
      title: "MyStampa",
      entries: [
        ...(e ? [["URL_MYSTAMPA", e.url] as [string, string]] : []),
        ...(e?.ipUrl ? [["URL_MYSTAMPA_IP", e.ipUrl] as [string, string]] : []),
        ...portEntry(e, "PORT_MYSTAMPA"),
      ],
    });
  }

  if (enabled("mynumeri")) {
    const e = urlOf("mynumeri");
    sections.push({
      title: "MyNumeri",
      entries: [
        ["AUTH_URL_NUMERI", derived.api.url],
        ...(e ? [["URL_MYNUMERI", e.url] as [string, string]] : []),
        ...(e?.ipUrl ? [["URL_MYNUMERI_IP", e.ipUrl] as [string, string]] : []),
        ...portEntry(e, "PORT_MYNUMERI"),
      ],
    });
  }

  if (enabled("myclienti")) {
    const e = urlOf("myclienti");
    sections.push({
      title: "MyClienti",
      entries: [
        ...(e ? [["URL_MYCLIENTI", e.url] as [string, string]] : []),
        ...(e?.ipUrl ? [["URL_MYCLIENTI_IP", e.ipUrl] as [string, string]] : []),
        ...portEntry(e, "PORT_MYCLIENTI"),
      ],
    });
  }

  if (enabled("dbgate")) {
    const e = urlOf("dbgate");
    sections.push({
      title: "DBGate",
      entries: [
        ["DBGATE_USER", secrets.DBGATE_USER!],
        ["DBGATE_PASSWORD", secrets.DBGATE_PASSWORD!],
        ...(e ? [["URL_DBGATE", e.url] as [string, string]] : []),
        ...(e?.ipUrl ? [["URL_DBGATE_IP", e.ipUrl] as [string, string]] : []),
        ...portEntry(e, "PORT_DBGATE"),
      ],
    });
  }

  return renderEnvFile(header, sections);
}
