import type { DerivedConfig } from "../derive.js";

/**
 * Starter nginx configuration for the advanced setup.
 *
 * The installer only adds the container and this template: hostnames, TLS and
 * routing are up to the developer. The proxy blocks are already SSE-safe.
 */
export function generateNginxConf(derived: DerivedConfig): string {
  const out: string[] = [];
  out.push("# nginx configuration generated by the MySagra installer (starter template).");
  out.push("# Edit it freely: hostnames, TLS certificates and routing are up to you.");
  out.push("# The proxy settings below are already tuned for SSE (no buffering, no timeouts).");
  out.push("#");
  out.push("# TLS: drop cert.pem/key.pem into ./certs (mounted read-only at /etc/nginx/certs)");
  out.push("# and uncomment the `listen 443 ssl` lines.");
  out.push("");

  out.push("map $http_upgrade $connection_upgrade {");
  out.push("    default upgrade;");
  out.push("    ''      close;");
  out.push("}");
  out.push("");

  for (const endpoint of derived.endpoints) {
    const upstream = `${endpoint.service.id}:${endpoint.service.port}`;
    const serverName = endpoint.service.subdomain
      ? `${endpoint.service.subdomain}.example.com`
      : "example.com";
    out.push(`# ── ${endpoint.service.label} ──`);
    out.push("server {");
    out.push("    listen 80;");
    out.push("    # listen 443 ssl;");
    out.push("    # ssl_certificate     /etc/nginx/certs/cert.pem;");
    out.push("    # ssl_certificate_key /etc/nginx/certs/key.pem;");
    out.push(`    server_name ${serverName};`);
    out.push("");
    out.push("    location / {");
    out.push(`        proxy_pass http://${upstream};`);
    out.push("        proxy_http_version 1.1;");
    out.push("        proxy_set_header Host $host;");
    out.push("        proxy_set_header X-Real-IP $remote_addr;");
    out.push("        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;");
    out.push("        proxy_set_header X-Forwarded-Proto $scheme;");
    out.push("        proxy_set_header Upgrade $http_upgrade;");
    out.push("        proxy_set_header Connection $connection_upgrade;");
    out.push("        # SSE: keep the stream open and unbuffered");
    out.push("        proxy_buffering off;");
    out.push("        proxy_cache off;");
    out.push("        proxy_read_timeout 24h;");
    out.push("        chunked_transfer_encoding off;");
    out.push("    }");
    out.push("}");
    out.push("");
  }

  return out.join("\n");
}
